import { chromium } from 'playwright';
import { mkdir, writeFile, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'), output=path.join(root,'verification');await mkdir(output,{recursive:true});
const base=process.env.AFTERLIGHT_URL||'http://localhost:5187',chrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';let executablePath;try{await access(chrome);executablePath=chrome}catch{}
const browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{})});
const report={startedAt:new Date().toISOString(),base,method:'Real profile/start/roll/continue UI and keyboard/pointer input. Direct simulation advancement shortens waits; fixtures align precision timing games.',checks:[],consoleErrors:[],pageErrors:[],failedRequests:[],screenshots:[]};
function observe(page,label){page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push({label,text:m.text()})});page.on('pageerror',e=>report.pageErrors.push({label,message:e.message}));page.on('requestfailed',r=>report.failedRequests.push({label,url:r.url(),error:r.failure()?.errorText}));}
async function check(name,fn){try{const details=await fn();report.checks.push({name,passed:true,details});console.log('PASS',name);return details}catch(e){report.checks.push({name,passed:false,error:e.stack||e.message});console.log('FAIL',name,e.message);return null;}}
async function shot(page,name,selector){const dest=path.join(output,name);if(selector)await page.locator(selector).screenshot({path:dest});else await page.screenshot({path:dest,fullPage:true});report.screenshots.push(name);}
async function ready(page){await page.goto(base);await page.waitForFunction(()=>window.afterlight?.minigames?.length===20);}
async function arcade(page){await page.locator('[data-nav="arcade"]').first().click();await page.waitForSelector('.game-card');}
async function start(page,index){await page.locator(`[data-practice="${index}"]`).click();await page.locator(`[data-character="${index%4}"]`).click();await page.locator('#player-name').fill('QA Traveler');await page.locator('#start-solo').click();await page.waitForSelector('#begin-minigame');assert.equal(await page.evaluate(()=>window.afterlight.state.phase),'minigame-intro');await page.locator('#begin-minigame').click();await page.waitForFunction(()=>window.afterlight.state.phase==='minigame'&&window.afterlight.state.game);await page.evaluate(()=>window.afterlight.state.countdown=0);await page.waitForFunction(()=>!document.querySelector('.stage-overlay'));}
async function press(page,key,ms=160){await page.keyboard.down(key);await page.waitForTimeout(ms);await page.keyboard.up(key);await page.waitForTimeout(40);}
async function finish(page){await page.evaluate(async()=>{const {stepGame}=await import('/src/minigames.js');const s=window.afterlight.state;s.countdown=0;for(let n=0;n<2000&&!s.game.done;n++)stepGame(s.game,{},1/60)});await page.waitForFunction(()=>window.afterlight.state.phase==='results');}
async function player(page){return page.evaluate(()=>JSON.parse(JSON.stringify(window.afterlight.state.game.players.find(p=>p.id==='local'))));}
async function controls(page,id){
 const before=await player(page);let details={};
 if(['inkfall','mothlight','raft','trace','shadow'].includes(id)){await press(page,'ArrowRight',180);const after=await player(page);assert.ok(after.x>before.x,`${id} right input moves`);details={xBefore:before.x,xAfter:after.x};if(id==='shadow'){await press(page,'Space',80);assert.ok((await player(page)).cooldown>0);}}
 else if(id==='sweep'){await page.keyboard.down('Space');await page.waitForTimeout(100);assert.ok((await player(page)).jump>0);await page.keyboard.up('Space');details={jumpTriggered:true};}
 else if(id==='rhythm'){await page.evaluate(()=>{window.afterlight.state.game.time=.77});await press(page,'Space',35);assert.ok((await player(page)).score>before.score);details={fixture:'first beat timing',score:(await player(page)).score};}
 else if(id==='maze'){await press(page,'ArrowRight',150);assert.ok((await player(page)).cx>before.cx);details={gridMoved:true};}
 else if(id==='memory'){await page.evaluate(async()=>{const {stepGame}=await import('/src/minigames.js');const g=window.afterlight.state.game;while(g.time<3.05)stepGame(g,{},1/60)});const p=await player(page);await press(page,['ArrowUp','ArrowRight','ArrowDown','ArrowLeft'][p.sequence[0]],80);assert.ok((await player(page)).answer>0);details={recalledFirstArrow:true};}
 else if(id==='redlight'){await press(page,'ArrowUp',180);assert.ok((await player(page)).progress>before.progress);details={progress:(await player(page)).progress};}
 else if(id==='tug'){await press(page,'Space',80);assert.ok((await player(page)).score>before.score);details={tapScores:true};}
 else if(id==='gallery'){await press(page,'ArrowRight',180);assert.ok((await player(page)).aim>before.aim);await press(page,'Space',80);assert.ok((await player(page)).shotTime>0);details={aimAndFire:true};}
 else if(id==='fishing'){await page.evaluate(()=>{const p=window.afterlight.state.game.players.find(p=>p.id==='local');p.phase=p.arc-.1});await press(page,'Space',30);assert.ok((await player(page)).score>before.score);details={fixture:'needle aligned with catch arc',catchScores:true};}
 else if(id==='balance'){await press(page,'ArrowRight',180);assert.ok((await player(page)).lean>before.lean);details={balanceInputChangesLean:true};}
 else if(id==='sorting'){await page.evaluate(()=>{const p=window.afterlight.state.game.players.find(p=>p.id==='local');p.parcel=p.bin});await press(page,'Space',80);assert.ok((await player(page)).score>before.score);details={fixture:'parcel matches selected bin',sortScores:true};}
 else if(id==='reaction'){await page.evaluate(()=>{const g=window.afterlight.state.game;g.state.signal='go';g.state.next=g.time+2;g.state.signalTime=g.time});await press(page,'Space',60);assert.ok((await player(page)).score>before.score);details={fixture:'true signal active',reactionScores:true};}
 else if(id==='potato'){await page.evaluate(()=>{const g=window.afterlight.state.game;g.state.holder=0;g.players[0].cooldown=0});await press(page,'Space',40);assert.ok((await player(page)).score>before.score+1);details={passScores:true};}
 else if(id==='crates'){await press(page,'ArrowRight',80);assert.ok((await player(page)).crateX>before.crateX);details={cratePushed:true};}
 else if(id==='orbit'){await press(page,'Space',60);assert.equal((await player(page)).dir,-before.dir);details={orbitReversed:true};}
 else if(id==='cipher'){await page.evaluate(()=>{const p=window.afterlight.state.game.players[0];p.symbol=p.code[p.dial]});await press(page,'Space',60);assert.ok((await player(page)).score>before.score);details={fixture:'matching tumbler selected',lockScores:true};}
 return details;
}
async function layout(page){return page.evaluate(()=>({viewport:innerWidth,pageWidth:document.documentElement.scrollWidth,canvas:document.querySelector('#game-canvas')?.getBoundingClientRect().toJSON(),overlay:document.querySelector('.stage-overlay')?.getBoundingClientRect().toJSON(),buttons:[...document.querySelectorAll('.stage-overlay button')].map(b=>({id:b.id,rect:b.getBoundingClientRect().toJSON()}))}));}
function overlayFits(value){assert.ok(value.pageWidth<=value.viewport+1,`horizontal overflow: ${value.pageWidth} > ${value.viewport}`);for(const b of value.buttons){assert.ok(b.rect.bottom<=value.overlay.bottom+1,`${b.id} bottom ${b.rect.bottom} clipped by overlay ${value.overlay.bottom}`);assert.ok(b.rect.top>=value.overlay.top,`${b.id} above overlay`);}return value;}
try{
 const desktop=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1}),page=await desktop.newPage();observe(page,'desktop');await ready(page);
 await check('desktop home shows cast and play modes',async()=>{assert.equal(await page.locator('.hero-character').count(),4);assert.equal(await page.locator('.mode-card').count(),3);await shot(page,'desktop-home.png');const sizes=await page.evaluate(async()=>Object.fromEntries(await Promise.all(['city','characters','props'].map(name=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve([name,{width:im.naturalWidth,height:im.naturalHeight}]);im.onerror=reject;im.src=`/assets/${name}.png`})))));assert.equal(Object.keys(sizes).length,3);return sizes;});
 await check('arcade has twenty playable cards',async()=>{await arcade(page);assert.equal(await page.locator('.game-card').count(),20);await shot(page,'desktop-arcade.png');return {cards:20};});
 const games=await page.evaluate(()=>window.afterlight.minigames);
 for(let index=0;index<games.length;index++){const g=games[index];await check(`arcade ${String(index+1).padStart(2,'0')} ${g.id}: UI, input, render, results`,async()=>{if(await page.evaluate(()=>window.afterlight.route)!=='arcade'){await ready(page);await arcade(page)}await start(page,index);assert.equal(await page.evaluate(()=>window.afterlight.state.game.id),g.id);const result=await controls(page,g.id);await shot(page,`game-${String(index+1).padStart(2,'0')}-${g.id}.png`,'#game-canvas');await finish(page);assert.equal(await page.locator('.result-row').count(),4);await page.locator('#arcade-back').click();await page.waitForSelector('.game-card');return result;});}
 await check('solo party completes three rounds using roll and continue buttons',async()=>{
  await page.locator('[data-play="solo"]').first().click();await page.locator('#rounds').selectOption('3');await page.locator('#player-name').fill('Night Tester');await page.locator('#start-solo').click();await page.waitForSelector('#roll-dice');assert.equal(await page.evaluate(()=>window.afterlight.state.totalRounds),3);await page.locator('#change-route').click();assert.equal(await page.evaluate(()=>window.afterlight.state.players[0].direction),-1);await page.locator('#use-item').click();assert.equal(await page.evaluate(()=>window.afterlight.state.players[0].boost),3);await shot(page,'desktop-board.png');const rounds=[];
  for(let r=1;r<=3;r++){await page.locator('#roll-dice').click();assert.equal(await page.evaluate(()=>window.afterlight.state.boardStage),'rolling');await page.evaluate(async()=>{const {stepParty}=await import('/src/board.js');const s=window.afterlight.state;for(let n=0;n<500&&s.phase==='board';n++)stepParty(s,.1)});await page.waitForSelector('#begin-minigame');await page.locator('#begin-minigame').click();await finish(page);rounds.push(await page.evaluate(()=>({round:window.afterlight.state.round,game:window.afterlight.state.game.id,results:window.afterlight.state.results})));if(r===1)await shot(page,'desktop-results.png');await page.locator('#continue-party').click();}
  await page.waitForFunction(()=>window.afterlight.state.phase==='finished');assert.equal(await page.locator('.result-row').count(),4);await shot(page,'desktop-finale.png');await page.locator('#finish-home').click();assert.equal(await page.evaluate(()=>window.afterlight.route),'home');return {rounds,returnedHome:true};
 });
 await check('pause freezes local simulation and resume restores it',async()=>{await arcade(page);await start(page,0);await page.locator('#match-menu').click();const t=await page.evaluate(()=>window.afterlight.state.game.time);await page.waitForTimeout(220);assert.equal(await page.evaluate(()=>window.afterlight.state.game.time),t);await page.locator('[data-close]').last().click();await page.waitForTimeout(130);assert.ok(await page.evaluate(()=>window.afterlight.state.game.time)>t);await page.keyboard.press('Escape');await page.locator('#quit').click();return {pauseVerified:true};});
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true}),phone=await mobile.newPage();observe(phone,'mobile');await ready(phone);
 await check('mobile home fits and arcade mode opens',async()=>{const l=await layout(phone);assert.ok(l.pageWidth<=390);await shot(phone,'mobile-home.png');await phone.locator('.mode-card[data-nav="arcade"]').click();assert.equal(await phone.locator('.game-card').count(),20);await shot(phone,'mobile-arcade.png');return l;});
 await check('mobile intro and start button fit in stage',async()=>{await phone.locator('[data-practice="0"]').click();await phone.locator('#start-solo').click();await phone.waitForSelector('#begin-minigame');await shot(phone,'mobile-intro.png');return overlayFits(await layout(phone));});
 await check('mobile touch movement changes player position',async()=>{await phone.locator('#begin-minigame').click();await phone.evaluate(()=>window.afterlight.state.countdown=0);await phone.waitForFunction(()=>!document.querySelector('.stage-overlay'));const before=await player(phone),b=await phone.locator('[data-input="right"]').boundingBox();const touch=await phone.context().newCDPSession(phone);await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2}]});await phone.waitForTimeout(230);await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await touch.detach();const after=await player(phone);assert.ok(after.x>before.x);await shot(phone,'mobile-playing.png');return {xBefore:before.x,xAfter:after.x};});
 await check('mobile results and buttons fit in stage',async()=>{await finish(phone);await shot(phone,'mobile-results.png');return overlayFits(await layout(phone));});
 await check('mobile results can return to arcade',async()=>{await phone.locator('#arcade-back').click();await phone.waitForSelector('.game-card');assert.equal(await phone.locator('.game-card').count(),20);return {returned:true};});
 await check('mobile three-round party reaches a fully visible finale',async()=>{await phone.locator('[data-play="solo"]').first().click();await phone.locator('#rounds').selectOption('3');await phone.locator('#start-solo').click();for(let round=1;round<=3;round++){await phone.locator('#roll-dice').click();await phone.evaluate(async()=>{const {stepParty}=await import('/src/board.js');const state=window.afterlight.state;for(let n=0;n<500&&state.phase==='board';n++)stepParty(state,.1)});await phone.waitForSelector('#begin-minigame');await phone.locator('#begin-minigame').click();await finish(phone);await phone.locator('#continue-party').click();}await phone.waitForFunction(()=>window.afterlight.state.phase==='finished');await shot(phone,'mobile-finale.png');const value=overlayFits(await layout(phone));await phone.locator('#finish-home').click();assert.equal(await phone.evaluate(()=>window.afterlight.route),'home');return value;});
 await check('no JavaScript exceptions',async()=>{assert.equal(report.pageErrors.length,0,JSON.stringify(report.pageErrors));return {pageErrors:0};});
 await check('no browser console errors',async()=>{assert.equal(report.consoleErrors.length,0,JSON.stringify(report.consoleErrors));return {consoleErrors:0};});
 await desktop.close();await mobile.close();
 const contact=await browser.newPage({viewport:{width:1600,height:1320}}),images=report.screenshots.filter(n=>n.startsWith('game-'));await contact.setContent(`<html><body style="margin:0;background:#e9e5d9;color:#222;font:14px Arial"><h1 style="margin:24px">AFTERLIGHT / Twenty verified minigame scenes</h1><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:12px;padding:0 24px 24px">${images.map(n=>`<figure style="margin:0"><img src="${base}/verification/${n}" style="display:block;width:100%"><figcaption style="padding:5px">${n.replace('game-','').replace('.png','')}</figcaption></figure>`).join('')}</div></body></html>`);await contact.waitForFunction(()=>[...document.images].every(i=>i.complete));await shot(contact,'minigame-contact-sheet.png');await contact.close();
}catch(error){report.fatal=error.stack||error.message;console.error(error);}finally{await browser.close();report.finishedAt=new Date().toISOString();report.passed=report.checks.filter(c=>c.passed).length;report.failed=report.checks.filter(c=>!c.passed).length;await writeFile(path.join(output,'browser-report.json'),JSON.stringify(report,null,2));await writeFile(path.join(output,'browser-report.md'),['# Afterlight browser verification','',`${report.passed} checks passed; ${report.failed} failed. ${report.pageErrors.length} JavaScript exceptions; ${report.consoleErrors.length} browser console errors.`,'',report.method,'',...report.checks.map(c=>`- ${c.passed?'PASS':'FAIL'} — ${c.name}${c.passed?'':': '+c.error.split('\n')[0]}`),'','Screenshots and the twenty-game contact sheet are in this directory.',''].join('\n'));console.log(JSON.stringify({passed:report.passed,failed:report.failed,pageErrors:report.pageErrors.length,consoleErrors:report.consoleErrors.length,fatal:report.fatal}));if(report.failed||report.fatal)process.exitCode=1;}
